### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by djmtype** [WebDevStudios/WordPress-Widgets-Refresh#7]
Activated widget in a fresh install of wp 3.6. Says "Nothing to see here yet." Am I missing something?

**Comment by richardtape** [comment]
Hi djmtype, We've literally just started along the road to changing widgets in WordPress. The plugin is simply a placeholder for the moment. Bear with us, we'll get there.

**Comment by djmtype** [comment]
Sorry, I misinterpreted the article.
